services:
  postgres:
    image: postgres:17
    container_name: quiet_groove
    restart: no
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reservations
    ports:
      - "5432:5432"
    volumes:
      - postgres_quiet_groove_data:/var/lib/postgresql/data

volumes:
  postgres_quiet_groove_data: